# Generated by Django 5.0.2 on 2024-03-03 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=12),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_status',
            field=models.CharField(choices=[('COMPLETE', 'completed'), ('INCOMPLETE', 'incomplete')], default='INCOMPLETE', max_length=12),
        ),
        migrations.AlterField(
            model_name='targetwallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
