# Generated by Django 5.0.2 on 2024-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_target_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_add_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_deadline',
            field=models.DateField(),
        ),
    ]
